export const SET_NAME_ACTION = 'SET_NAME_ACTION';
export const SET_TEXT_ACTION = 'SET_TEXT_ACTION';
export const SET_RATING_ACTION = 'SET_RATING_ACTION';
export const CLEAR_FORM_ACTION = 'CLEAR_FORM_ACTION';
